<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAKrh3ri\srcApp_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAKrh3ri/srcApp_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAKrh3ri.legacy');

    return;
}

if (!\class_exists(srcApp_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAKrh3ri\srcApp_KernelTestDebugContainer::class, srcApp_KernelTestDebugContainer::class, false);
}

return new \ContainerAKrh3ri\srcApp_KernelTestDebugContainer([
    'container.build_hash' => 'AKrh3ri',
    'container.build_id' => '26181580',
    'container.build_time' => 1565943821,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAKrh3ri');
