version: "3"
services: 
  web:
    image: nginx
    volumes: 
      - ".:/app"
      - "./docker-dev/nginx/site.conf:/etc/nginx/conf.d/default.conf"
      - "./docker-dev/php.ini:/usr/local/etc/pap/conf.d/custom.ini"
    depends_on: 
      - php
    ports: 
      - "8080:80"
  php:
    build:
      context: .
      dockerfile: docker_dev/Dockerfile
    volumes: 
      - ".:/app"
      - "./docker-dev/php.ini:/usr/local/etc/pap/conf.d/custom.ini"
    #depends_on: 
      #- db
  #db:
    #image: mariadb
    #environment: 
      #MYSQL_ROOT_PASSWORD: root
    #ports: 
     # - "3307:3306"

