<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'annotations.reader' shared service.

include_once $this->targetDirs[3].'\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\Reader.php';
include_once $this->targetDirs[3].'\\vendor\\doctrine\\annotations\\lib\\Doctrine\\Common\\Annotations\\AnnotationReader.php';

$this->privates['annotations.reader'] = $instance = new \Doctrine\Common\Annotations\AnnotationReader();

$instance->addGlobalIgnoredName('required', ($this->privates['annotations.dummy_registry'] ?? $this->load('getAnnotations_DummyRegistryService.php')));

return $instance;
